### ISSUE TITLE
namespace error

### ISSUE THREAD

**Issue by Brendan-McWalters** [rstudio/d3heatmap#12]
when running the basic example 
```
library(d3heatmap)
d3heatmap(mtcars, scale = "column", colors = "Spectral")
```
I get the error:
```
Error: 'col_numeric' is not an exported object from 'namespace:scales'
```
I'm not even sure how to begin to debug this.

**Comment by jcheng5** [comment]
You need to upgrade the scales package: `install.packages("scales")`

I'm surprised it wasn't automatically upgraded when you installed d3heatmap--did you install d3heatmap from CRAN or from GitHub?
