### ISSUE TITLE
Colour bars

### ISSUE THREAD

**Issue by TomKellyGenetics** [rstudio/d3heatmap#13]
Would it be possible to enable colour bars for `d3heatmap`, the annotation with `ColSideColors` and `RowSideColors` is one of the most useful features of `heatmap.2` for me. Would be great to take that interactive, hopefully wider adoption if interactive heatmaps are compatible with existing workflows.

Looks great though, really excited to see this get used.

Cheers,
Tom K

**Comment by kmakat** [comment]
Agree, that row and column annotations like those provided in heatmap.2 or NMF::aheatmap would be very useful.

Nice package!
Kemal

**Comment by TomKellyGenetics** [comment]
I've had a go at modifying these layout options myself (to send in a pull request) but would take me a while since the `d3heatmap` code differs considerably from the likes of `heatmap.2` (having tinkered with adding multiple colours bars). Keen to see where this goes don't have much time to figure it out. Let me know if anyone intends to do this or could show where the layout settings are. I'd be happy with static colour bars on an interactive heatmap.

Cheers,
Tom K

**Comment by jcheng5** [comment]
@TomKellyGenetics Unfortunately the hard part is not modifying the R code, but the JavaScript code that does the d3 stuff. I want to take a pass at this but am so busy with other projects at the moment...

**Comment by jcheng5** [comment]
Here's the JS code, BTW. If there happen to be any sophisticated JS/d3 developers out there who want to take a serious pass at a pull request, I'm happy to talk them through the structure of the code.

**Comment by TomKellyGenetics** [comment]
Sorry, I'm an absolute novice with JS so can't help much there. Will keep an eye on this, would love to see it revisited or taken up by another JS developer. Might be able to help with the R component, you seem to have that covered though :-) 

Thanks for taking the time to consider this feature,
Tom K

**Comment by khughitt** [comment]
:+1:  Thanks for implementing, Joe!

**Comment by TomKellyGenetics** [comment]
Awesome! I'm so excited about this!
