### ISSUE TITLE
Customize Tooltip Field Names

### ISSUE THREAD

**Issue by iankloo** [rstudio/d3heatmap#14]
The 'on hover' feature of the tooltip currently displays 'Row', 'Column', and 'Value' as labels within the box.  It would be helpful to be able to change these to match the specific case.

**Comment by mcjudd** [comment]
I would appreciate such functionality as well. However, you can work around it for the time being by going to where your R libraries are installed, finding the folder "d3heatmap" and then navigating to "htmlwidgets/lib/d3heatmapcore" and editing heatmap.js -- the statements after the following line dictate the formatting of the tooltip:

var tip = d3.tip()
        .attr('class', 'd3heatmap-tip')
        .html(function(d, i) { // edit after here!
})

**Comment by mcjudd** [comment]
Just an update to note that the argument `cellnote` for the `d3heatmap` function allows you to supply a matrix the same size as the data.frame being visualized with the text you'd like each cell to display on hover. More details via `?d3heatmap`

**Comment by zhangz19** [comment]
I have exactly the same concern. Is it possible to change "row", "col" and "value" into specific dimension names? Which would be very helpful. Not sure if this could be done in shiny when rendering d3heatmap.

**Comment by talgalili** [comment]
Hi @iankloo 

The heatmaply R package is a new implementation of interactive cluster heatmaps in R which relies on the plotly R package. This is based on a fork of my work in d3heatmap.

The package is availabale from CRAN:
https://cran.r-project.org/package=heatmaply

The feature you've requested is now available by using the following code:
```r
library(heatmaply)
heatmaply(mtcars, label_names = c("x_name", "y_name", "some_value"))
```

![image](https://cloud.githubusercontent.com/assets/976006/25064547/fa663e24-2204-11e7-9f66-447a3582017e.png)

**Comment by iankloo** [comment]
Looks like there are enough good ways around this to close this down.  Thanks for the responsiveness and help!

**Comment by kaixis** [comment]
I have R version 3.2.5 and plotly version 4.7.0, why can't I import heatmaply package?
