### ISSUE TITLE
hover over tooltip in firefox

### ISSUE THREAD

**Issue by natrot** [rstudio/d3heatmap#15]
Hi Joe

Thanks for this, I never used heatmaps, but I tried this new widget and it really works nice.

I picked up that the hover over feature (that gives the row and column name an the actual value)  dont work in the firefox browser. Works perfect in Rstudio and chrome. I dont know bout IE, I never even test anything in IE.

Can you please have a look.

Thanks
Natrot

**Comment by jcheng5** [comment]
I can't reproduce this, the tooltips work fine for me in Firefox. Can you see if there are any errors in Firefox's error console? Also what exact Firefox version and what operating system? Thanks.

**Comment by jcheng5** [comment]
Actually please comment on issue #5, thanks.
