### ISSUE TITLE
'col_numeric' is not an exported object from 'namespace:scales'

### ISSUE THREAD

**Issue by hugh1li** [rstudio/d3heatmap#16]
Install and load packages d3heatmap and run the sample 
d3heatmap(mtcars, scale = "column", colors = "Blues")

Error above happens.

**Comment by jcheng5** [comment]
Try `install.packages("scales")`, restart R, and try again.

**Comment by hugh1li** [comment]
I tried before you told. It didn't work.

**Comment by jcheng5** [comment]
What does `packageVersion("scales")` return? If not [0.2.5](http://cran.r-project.org/web/packages/scales/index.html), can you try a different CRAN mirror?

**Comment by hugh1li** [comment]
IT worked. Thanks!

**Comment by MarkEdmondson1234** [comment]
Hi, I'm getting this error with 0.2.5 scales installed:

    > d3heatmap(result_matrix)
    Error: 'col_numeric' is not an exported object from 'namespace:scales'

    > packageVersion("d3heatmap")
    [1] ‘0.6.0’
    > packageVersion("scales")
    [1] ‘0.2.5’

**Comment by talgalili** [comment]
@MarkEdmondson1234  - could you please re-install "scales" and check if that helps?
Also, does it happen on other datasets than result_matrix?

**Comment by MarkEdmondson1234** [comment]
I installed a newer version of htmlwidgets(), and that worked, thanks :)
