### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by pssguy** [rstudio/d3heatmap#2]
From README

    if (!require(devtools)) {
      install.packages("devtools")
    }
    devtools::install_github("rstudio/d3-heatmap")

    Downloading github repo rstudio/d3-heatmap@master
    Error in download(dest, src, auth) : client error: (404) Not Found

Tried without hyphen a la repo name

    devtools::install_github("rstudio/d3heatmap")

    Downloading github repo rstudio/d3heatmap@master
    Installing d3heatmap
    Error in isNamespaceLoaded(pkg) : 
      attempt to use zero-length variable name

**Comment by stanstrup** [comment]
Same here.

**Comment by jcheng5** [comment]
Should be fixed now, thanks.
