### ISSUE TITLE
Correlation distance

### ISSUE THREAD

**Issue by schroederJ** [rstudio/d3heatmap#27]
Can the distance for clustering be generated based on pearson correlation?

**Comment by jcheng5** [comment]
The `distfun` argument can be used for this. Here's an example for heatmap.2 (d3heatmap works the same way):

https://stat.ethz.ch/pipermail/bioconductor/2009-July/028898.html

**Comment by jcheng5** [comment]
The `distfun` argument can be used for this. Here's an example for heatmap.2 (d3heatmap works the same way):

https://stat.ethz.ch/pipermail/bioconductor/2009-July/028898.html
