### ISSUE TITLE
Add main title and axes labels

### ISSUE THREAD

**Issue by makman7** [rstudio/d3heatmap#40]
xlab ylab and title not displaying in d3heatmap()..

**Comment by csrvermaak** [comment]
:+1:

**Comment by aemoor** [comment]
+1

**Comment by kbeck527** [comment]
+1

**Comment by aradhyakasat** [comment]
has this been implemented?

**Comment by Chuck-UGA** [comment]
+1

**Comment by talgalili** [comment]
Hi all,
You may be interested to know that the latest version of [heatmaply](https://cran.r-project.org/package=heatmaply) (0.7.0) now includes xlab/ylab/main parameters. Here is an example code and a screenshot of the interactive output:

```r
library(heatmaply)
heatmaply(mtcars, xlab = "Features", ylab = "Cars", 
		main = "An example of title and xlab/ylab",
		margins = c(60,100,40,20) )
```

![image](https://cloud.githubusercontent.com/assets/976006/22503400/3bc2773a-e87a-11e6-8224-b31acaede2f4.png)

**Comment by d8aninja** [comment]
+1
