### ISSUE TITLE
d3 heatmap example error

### ISSUE THREAD

**Issue by j450h1** [rstudio/d3heatmap#48]
`library(d3heatmap)`
`d3heatmap(mtcars, scale = "column", colors = "Spectral")`
`Error in rowMeans(x, na.rm = na.rm) : 'x' must be numeric`

Any advice?

**Comment by talgalili** [comment]
What is your  
sessionInfo()
?

If you are not using d3heatmap version 0.6.1, please install the latest version of d3heatmap and try again.

**Comment by opinonfischer** [comment]
Have the exact same problem and downloaded the latest version of d3heatmap

**Comment by ryanfortinOC** [comment]
Any update on this?

**Comment by j450h1** [comment]
Updated to latest version. All good now. Thanks!

**Comment by cattystats** [comment]
Updated to latest version and am still getting the same error. df I'm plotting is a factor in first column and all others variables are num

Error in rowMeans(x, na.rm = na.rm) : 'x' must be numeric
 [1] d3heatmap_0.6.1.1

**Comment by talgalili** [comment]
Hello there,
The input to d3heatmap must be a numeric matrix. The newer heatmaply R package can also deal with data.frame objects which includes factor columns (it will add them as a side notation automatically).


Tal

**Comment by mars188** [comment]
Hello, I am facing the same issue as above when using d3heatmap. Here is the error:

Error in rowMeans(x, na.rm = na.rm) : 'x' must be numeric

My first column is pathway name (string) but rest of all columns are numeric. I am trying to plot a heatmap. I downloaded the latest version of d3heatmap. 

I will really appreciate any help, please.
