### ISSUE TITLE
tooltip doesn't work in firefox

### ISSUE THREAD

**Issue by FrissAnalytics** [rstudio/d3heatmap#5]
Hi,

I noticed that in Shiny apps the tooltip doesn't work in the latest firefox (38.0.1) browser. It shows "undefined" instead of a value. The widget does work in Chrome and IE by the way. 

I think it would also be nice to highlight both matching row and column names when hovering over a cell. Especially on larger matrices currently it is hard to tell on which row and column you are hovering over.

kind regards, Herman

**Comment by jcheng5** [comment]
Does this work? http://rpubs.com/jcheng/nba4

If so, can you provide your sample Shiny+d3heatmap code where Firefox isn't working? It's working for me.

Thanks!

**Comment by natrot** [comment]
I used your link above, doesnt show anything in firefox. 
I use Firefox 38.0.5 on my Mac, didnt test on a windows machine.

**Comment by talgalili** [comment]
@jcheng5 - I confirm this bug. I get the same problem (no hover tooltip) on my machine (Windows 7, firefox 38.0.5).

**Comment by jcheng5** [comment]
OK, I get repro on Firefox 38.0.5. (I was on 40.0a apparently)

**Comment by HermanSontrop** [comment]
yep, works for me too now!
