### ISSUE TITLE
Multiple d3heatmaps not displaying in conditional

### ISSUE THREAD

**Issue by kbeck527** [rstudio/d3heatmap#54]
When trying to plot multiple d3heatmaps within a conditional, the HTML that is generated only plots the final heat map. Below is code for an Rmd to reproduce the bug.

    ---
    title: "test"
    output: html_document
    ---
    
    This is an R Markdown document. 
    
    ```{r}
    require(d3heatmap)
    myVar = TRUE
    if (myVar == TRUE) {
      d3heatmap(mtcars, col = "Spectral")
      d3heatmap(mtcars, col = "Blues")
    }
    ```

If the heat maps are outside of a conditional, multiple will appear in the knitted html file. Has anyone else run into this? Any help would be appreciated.

    sessionInfo()
    R version 3.2.3 (2015-12-10)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.11.3 (El Capitan)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] d3heatmap_0.6.1.1
    
    loaded via a namespace (and not attached):
     [1] htmlwidgets_0.6 magrittr_1.5    htmltools_0.3   tools_3.2.3     base64enc_0.1-3
     [6] yaml_2.1.13     stringi_1.0-1   rmarkdown_0.9.5 knitr_1.12.3    stringr_1.0.0  
    [11] digest_0.6.9    evaluate_0.8.3  png_0.1-7

**Comment by timelyportfolio** [comment]
I think using `tagList()` from `htmltools` will solve your problem.

Try

```
library(htmltools)
require(d3heatmap)
myVar = TRUE
if (myVar == TRUE) {
  d3heatmap(mtcars, col = "Spectral")
  d3heatmap(mtcars, col = "Blues")
}
```

**Comment by kbeck527** [comment]
Thank you especially for the quick response. This is a nice work around. Am I missing something or should I be able to generate multiple d3heatmap just like any plot within a code chunk though?

**Comment by timelyportfolio** [comment]
I can't say for sure, but I'm almost positive we are limited to one `htmlwidget` per code chunk.  This might help explain https://github.com/ramnathv/htmlwidgets/pull/110.

**Comment by kbeck527** [comment]
That's what I initially thought too. But this works just fine.

```{r}
require(d3heatmap)
d3heatmap(mtcars, col = "Spectral")
d3heatmap(mtcars, col = "Blues")
```

**Comment by jcheng5** [comment]
Calling d3heatmap doesn't actually render a heatmap, it just creates and returns one--just like all htmlwidgets. (This is different than plots which actually get created when you call plot()). It just so happens that what knitr chooses to do with top-level expressions, is print (actually knit_print) them. 

So what you did was akin to this:

```
if (myVar == TRUE) {
  1
  2
}
```

And wondering why only 2, not 1, was printed. And tagList is akin to wrapping these numbers in c(1, 2). 

So the limitation if you want to call it that, is that an if() block only ever returns its last expression.

**Comment by kbeck527** [comment]
That makes perfect sense. Thank you!
