### ISSUE TITLE
 missing file link ‘shinyWidgetOutput’

### ISSUE THREAD

**Issue by NahuelGrasso** [rstudio/d3heatmap#73]
Hello, 
I am trying to install this package in an R server (red hat) that doesn't have internet connection.
I receive the following message:
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘d3heatmap’ ...
** package ‘d3heatmap’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘d3heatmap’
    finding HTML links ... done
    d3heatmap                               html
    d3heatmapOutput                         html
Rd warning: /tmp/Rtmp0pvtkW/R.INSTALL69e8153995d9/d3heatmap/man/d3heatmapOutput.                                                                                        Rd:16: missing file link ‘shinyWidgetOutput’
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (d3heatmap)
Making 'packages.html' ... done

Is this error due to a bad installation of dependencies like dendextend?
Any advice?
Thanks

**Comment by jcheng5** [comment]
Hmmm, I don't know--I don't get this problem on my installation. It looks like the install succeeded despite the warning though; does it work?

**Comment by NahuelGrasso** [comment]
Actually, in my own laptop, it works perfectly, but in the server doesn't.
So.., back to the problem, although the instalation says it worked, I get the following error when I launch the shiny app:
**ERROR: could not find function "d3heatmapOutput"**
It makes sense because the missing file link is shinyWidget**Output**.
I'll try to install again the dependencies with an updated version from github and see what happen.
If you have any clue or advice let me know.
Thanks

**Comment by NahuelGrasso** [comment]
Hi, I solved the problem!
maybe Rookie mistake.
I checked that the method **shinyWidgetOutput** was from the **htmlwidgets** package, so I just added it to the global.R file and worked!
Thanks
