### ISSUE TITLE
Colors not being mapped correctly

### ISSUE THREAD

**Issue by hherrada** [rstudio/d3heatmap#76]
Hello, I am implementing a correlation matrix and am using colorRamp to interpolate among green, white and red. `d3heatmap` is not mapping the colors appropriately. Here is sample code replicating the issue:

Note that cell 2,1 should have a green tone but has a red tone instead.
````
Rho <- matrix(c(1,.1,-.2,NA,1,-.7,NA,NA,1), ncol = 3)

d3heatmap(Rho, Rowv = FALSE, Colv = FALSE, distfun = NULL, dendrogram = "none",
          colors = colorRamp(c("red","white","green")))

**Comment by jcheng5** [comment]
The colors are scaled relative to the values in your matrix, so in this case, the range is from `-.7` to `1`. Since `.1` falls closer to the min than to the max, it has a red cast.

It looks to me like this is different than heatmap.2 which scales to `±abs(max(range(x)))` if there are negative values in the matrix. Is that a no-brainer better default?

**Comment by hherrada** [comment]
Not sure what would be a better default but the package `corrplot` handles the color palette well for correlation matrices. Do you think the same default can be implemented in d3?

Thank you

```
Rho <- matrix(c(1,.1,-.2,.1,1,-.7,-.1,-.7,1), ncol = 3)
corrplot(Rho, method="color", col=colorRampPalette(c("red","white","green"))
```

**Comment by hherrada** [comment]
Ok, the following worked. I think we can get away from changing anything. Thanks!

```
Rho <- matrix(c(1,.1,-.2,.1,1,-.7,-.1,-.7,1), ncol = 3)

Min <- min(Rho)

Color <- colorRampPalette(c("red","white","green"))
Color <- Color(100)

myfun <- function(x) {

  tmp <- (Min+1)/(1-Min)
  
  newcorr <- (x + tmp) / (1 + tmp)
  newcorr[newcorr <= 0] <- 0
  newcorr[newcorr >= 1] <- 1 - 1e-16
  
  Color[floor(newcorr * length(Color)) + 1]
  
}

d3heatmap(Rho, Rowv = FALSE, Colv = FALSE, distfun = NULL, dendrogram = "none", colors = myfun)
``
