### ISSUE TITLE
additional margin space for longer labels

### ISSUE THREAD

**Issue by seraphim711** [rstudio/d3heatmap#80]
How does one modify the margin space to accommodate longer row/column label names?

`    tags$div(style="width: 700px; margin-left: 10px; margin-right: 100px; margin-bottom: 100px",
    d3heatmapOutput(ns("heatmap"), width="100%", height="720px"))`

**Comment by talgalili** [comment]
Hi @seraphim711 

The heatmaply R package is a new implementation of interactive cluster heatmaps in R which relies on the plotly R package. This is based on a fork of my work here in d3heatmap.

The package is availabale from CRAN:
https://cran.r-project.org/package=heatmaply
With the following detailed vignette:
https://cran.r-project.org/web/packages/heatmaply/vignettes/heatmaply.html


The feature you've requested is now available by using the following code:

```r
library(heatmaply)
heatmaply(mtcars, xlab = "Features", ylab = "Cars", 
        main = "An example of title and xlab/ylab",
        margins = c(60,100,40,20))
```

![image](https://user-images.githubusercontent.com/976006/27735625-4b0777be-5da9-11e7-90af-da1dffd95d4f.png)

**Comment by seraphim711** [comment]
Thank you very much! This is an useful tool indeed 👍

**Comment by tilley-charles** [comment]
For anyone else that stumbles on this, in January 2021 there are `d3heatmap::d3heatmap` options called `xaxis_height` and `yaxis_width` (specified in pixels) that helped me address this issue.
